### ISSUE TITLE
default timeframes + favorites

### ISSUE THREAD

**Issue by algazarra** [coinigy/coinigy-issues#1]
Hi William,

morticia here ;) this is my github profile. Please check this out:
![timeframe coinigy](https://cloud.githubusercontent.com/assets/7598320/6631491/1150a340-c91f-11e4-8b87-5ea5668b6b66.PNG)

Even though there's the optional 3 dots to choose other timeframes, there's no way of quickly access, say 6h and 12h on Coinigy. At least that I'm aware of. Also, if you want to quickly toggle between those two (I believe common) timeframes, you have to input the value manually. It's time consuming and a distraction. Am I missing something? Is there a way to this?

ps: Since I'll be suggesting and submitting issues regularly, it would be cool if I could label the issue as bug, enhancement, bells & whistles, etc. You'd have to give me certain permissions on this repo. But since this is an issues only repo, maybe there's no problem.

**Comment by williamkehl** [comment]
We just deployed a change to include 6H and 12H timeframes. Make sure you clear your cache and/or run localStorage.clear(); in your console to flush the charting library.

**Comment by algazarra** [comment]
Perfect William! don't forget to close the issue after it's solved ;)
ps: on the right panel on this page you have "labels", make sure to add "bug, enhancement, bells & whistles, etc" so that the user can label the issue correctly while submitting.
