### ISSUE TITLE
volume bar colors

### ISSUE THREAD

**Issue by algazarra** [coinigy/coinigy-issues#2]
is it possible to use the same colors for volume bars as for candlesticks? the two tones of blue make it harder to distinguish who's who.

**Comment by dpoloner** [comment]
Yes, click the "gear" icon next to volume and you'll be able to change the bar colors. 

Screenshot:
![image](https://cloud.githubusercontent.com/assets/1824518/7023806/a6aa51a6-dcfd-11e4-86b4-e31d49ce2be5.png)

**Comment by williamkehl** [comment]
Yes, click the "gear" icon next to volume and you'll be able to change the bar colors.

Screenshot:
![image](https://cloud.githubusercontent.com/assets/998904/7023823/c5da1bce-dcfd-11e4-9517-a3d1bcd5d341.png)

**Comment by algazarra** [comment]
Ohh! Perfect!
