### ISSUE TITLE
ichimoku cloud fill

### ISSUE THREAD

**Issue by algazarra** [coinigy/coinigy-issues#3]
would it be possible to add fill to the cloud? It would make it easier and faster to read.

![2015-04-07-120532_1680x999_scrot](https://cloud.githubusercontent.com/assets/7598320/7021921/748d527e-dd1e-11e4-9346-95338fa31744.png)

![2015-04-07-120627_1680x1050_scrot](https://cloud.githubusercontent.com/assets/7598320/7021931/8eee55a0-dd1e-11e4-9186-8253b0fa9bf3.png)

**Comment by williamkehl** [comment]
Similar thing, clicking the gear will give you the ability to edit the fill color on Ichimoku: 
![image](https://cloud.githubusercontent.com/assets/998904/7024225/cec6a3d0-dd00-11e4-9ab5-258ffe4f4554.png)

I'm not sure if the color changes based on positive/negative though. But we do have a "custom" indicator loaded called CM_Enhanced_Ichimoku that does that. 

There's currently an issue with the custom indicators preventing them from showing up each time, though. So if you don't see it in the indicator list, you might need to refresh a few times. Hope that helps!

**Comment by algazarra** [comment]
perfect william!
